name: Deploying

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed

jobs:
  if_merged:
    name: Checks if successfully merged
    if: github.event.pull_request.merged == true

    steps:
      - run: echo The PR was merged

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: if_merged

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "myworkoutbuddyapp"
          heroku_email: "healyr@student.unimelb.edu.au"
      - run: echo Deployed successfully.
